############################
## CHANGE THESE
############################

baseURL: 'https://dblencowe.github.io/dblencowe.wtf'
title: dblencowe.wtf

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


